### PR TITLE
64-bit SheepShaver for macOS

### PR DESCRIPTION
**Pull request by kanjitalk755**
I have changed PR branch.

### CODE REVIEW

**Comment by ianfixes** [comment]
Looks like this has been open for a while.  I'd be glad to help you merge it into a fork I've set up at https://github.com/emaculation/SheepShaver (which will take some rewriting of git history).  Would you be comfortable setting up a `.travis.yml` file that captures your build process?

**Comment by kanjitalk755** [comment]
I'm not planning to introduce Travis CI for my repo.

**Comment by ianfixes** [comment]
> Would you be comfortable setting up a .travis.yml file that captures your build process?

I think I was unclear in the way I asked this.  

I've set up cross-platform CI on my own fork, and I'd like to use the same commands that you use in your own build process.  What commands are those?  Or, what existing documentation are you following in order to compile SheepShaver on various platforms?

My goal is to make it easier for everyone to collaborate on this project, and automated testing is at the top of my list.

**Comment by kanjitalk755** [comment]
To build my repo, see README.md.

**Comment by ianfixes** [comment]
Yup, I didn't see a README in this PR, but after commenting I noticed that your personal fork had the info.  Thanks 😄

**Pull request closed without merging**
