### PR TITLE
Add Travis CI configuration file and README.md status.

### PR DESCRIPTION
**Pull request by rickyzhang82**
In README.md, you need to modify URL link that you register in Travis CI. I don't know your link.

I tested it in my branch. The Travis CI script works for BII.

### CODE REVIEW

**Comment by dcoshea** [comment]
> In README.md, you need to modify URL link that you register in Travis CI. I don't know your link.

@rickyzhang82 Sorry, I've never actually used Travis before, so I'm a bit clueless here, but I see in https://raw.githubusercontent.com/cebix/macemu/master/README.md that the URLs still include your username.  I assume from what you said above that perhaps what is required is that @asvitkine needs to create his own account on the Travis site and tell it to build https://github.com/cebix/macemu/ ?  I assume that as it is the "build passing" image is referring to whether _your_ fork of macemu is passing the build, not whether the main cebix one is?  If @asvitkine needs to do more setup on the Travis site, perhaps you could provide him with some information about what he needs to do.

Anyway, it is great to see CI being enabled!

**Comment by rickyzhang82** [comment]
@dcoshea That's true. The status image is still pointing to the branch in my repo.
@asvitkine is required to activate Travis CI manually with a few clicks.
There are tons of doc/user guide online. [RTFM]( https://github.com/mbonaci/mbo-storm/wiki/Integrate-Travis-CI-with-your-GitHub-repo#integrate-your-github-project-with-travis-ci)

**Comment by asvitkine** [comment]
It doesn't look like I can activate it either, since it's under cebix and
not me. It doesn't show up in the Travis UI for me.

**Comment by ianfixes** [comment]
@asvitkine I've forked this repo (and split it up) so that we can have CI.  

* https://github.com/emaculation/BasiliskII [Build Status](https://travis-ci.org/emaculation/BasiliskII) (note the URL!)
* https://github.com/emaculation/SheepShaver
* https://github.com/emaculation/cxmon

It looks like I can support automated CI builds for Ubuntu, OSX, FreeBSD, and Windows (in parallel).  Can you point me to the proper build instructions for those platforms?

**Pull request merged**
