### PR TITLE
Haiku: preliminary x86_64 support

### PR DESCRIPTION
**Pull request by miqlas**

### CODE REVIEW

**Comment by miqlas** [comment]
Builds and the GUI runs onx AMD64 but crashes with black window. Maybe i made something wrong, who knows.

**Comment by MaddTheSane** [comment]
Have you looked at all the data-types? BeOS, IIRC, uses LP64, meaning that `long`s are now 64-bit, as opposed to 32-bit in 32-bit mode.

**Comment by miqlas** [comment]
No, but thanks for the explanation. Sadly kind of changes like that is well beyond my capability.

**Comment by miqlas** [comment]
I think i close this for now.

**Pull request closed without merging**
